-- Drop existing views/functions if any
DROP FUNCTION IF EXISTS increment_vote_count(TEXT);

-- Recreate votes with BIGINT quote_id
DROP TABLE IF EXISTS votes;
CREATE TABLE votes (
  id         BIGSERIAL PRIMARY KEY,
  quote_id   BIGINT      NOT NULL,
  ip_hash    TEXT        NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Recreate quote_stats with BIGINT quote_id
DROP TABLE IF EXISTS quote_stats;
CREATE TABLE quote_stats (
  quote_id   BIGINT  PRIMARY KEY,
  vote_count INTEGER NOT NULL DEFAULT 0
);

-- Recreate quotes with BIGINT Identity ID
DROP TABLE IF EXISTS quotes;
CREATE TABLE quotes (
  id                 BIGINT      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  quote_vi           TEXT        NOT NULL CHECK (char_length(trim(quote_vi)) > 0),
  quote_en           TEXT        NOT NULL CHECK (char_length(trim(quote_en)) > 0),
  author             TEXT        NOT NULL CHECK (char_length(trim(author)) > 0),
  source             TEXT        NOT NULL CHECK (char_length(trim(source)) > 0),
  source_url         TEXT,
  category           TEXT[]      NOT NULL DEFAULT '{}',
  tags               TEXT[]      NOT NULL DEFAULT '{}',
  year               INTEGER,
  verified           BOOLEAN     NOT NULL DEFAULT false,
  contributor_github TEXT,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Re-apply indexes
CREATE INDEX quotes_year_idx ON quotes (year DESC NULLS LAST);
CREATE INDEX quotes_category_gin_idx ON quotes USING GIN (category);
CREATE UNIQUE INDEX votes_ip_hash_quote_id_idx ON votes (ip_hash, quote_id);
CREATE INDEX votes_ip_hash_created_at_idx ON votes (ip_hash, created_at);

-- RLS Policies
ALTER TABLE quotes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public read" ON quotes FOR SELECT USING (true);

-- Recreate RPC
CREATE OR REPLACE FUNCTION increment_vote_count(p_quote_id BIGINT)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
  INSERT INTO quote_stats (quote_id, vote_count)
  VALUES (p_quote_id, 1)
  ON CONFLICT (quote_id)
  DO UPDATE SET vote_count = quote_stats.vote_count + 1;
END;
$$;
